### ISSUE TITLE
PHP 8.2 not working

### ISSUE THREAD

**Issue by DanielMcAssey** [php-actions/composer#104]
Hey trying to use GitHub actions with a composer dependency to php 8.2, I get the following in the action:

```
Your Composer dependencies require a PHP version ">= [8](https://github.com/GLOKON/qassist-app/actions/runs/5692887695/job/15430815466#step:8:9).2.0". You are running 8.1.2-1ubuntu2.13.

PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.2.0". You are running 8.1.2-1ubuntu2.13
```

This is the action

```
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: '8.2'
          php_extensions: gd zip sodium intl soap bcmath
          dev: yes
```
