### ISSUE TITLE
Problems trying to provide missing PHP extensions

### ISSUE THREAD

**Issue by devdrops** [php-actions/composer#109]
Hi! I'm running this action on a private project, Laravel based, and I have the persistent failure below:

![image](https://github.com/php-actions/composer/assets/1259313/6cad14c4-320c-4eab-9617-01cfc3242b51)

I've did updated the Composer dependencies:

![image](https://github.com/php-actions/composer/assets/1259313/5f64be68-4239-4370-bba9-787a5da98974)

But still this issue insists. Below is my actions file, where I've tried to provide the missing `zip` extension:

```yaml
name: PHPStan/Larastan Analysis

on:
  pull_request:
    branches:
      - staging

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          php_extensions: zip
          configuration: phpstan.neon
          memory_limit: 1G
```

Any help is really appreciated :wink:
