### ISSUE TITLE
Error: ACTION_TOKEN variable not set

### ISSUE THREAD

**Issue by LukeSavefrogs** [php-actions/composer#110]
Running the following causes the workflow to fail with the error in the subject:
```yaml
- name: Install composer dependencies
  uses: php-actions/composer@v6
  with:
    php_version: '8.2'
    args: --no-dev --no-interaction --prefer-dist --optimize-autoloader
  env:
    ACTION_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
