### ISSUE TITLE
Extensions not working

### ISSUE THREAD

**Issue by oti-adjei** [php-actions/composer#111]
Hi, I'm a bit new to GitHub Actions and I'm using the composer version to include PDO as well as PHPunit in my .yml
I get this error when I run my Github Action:
```
13) App\test\model\ProductTest::testUpdateProduct
PDOException: could not find driver
```
So far this is my .yml:
```
name: CI

on:
  push:
    branches:
      - OOP
jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3   
      - uses: php-actions/composer@v6
        with:
          php_version: "8.2"
          php_extensions: pdo_mysql
      - name: PHPUnit Tests
        uses: php-actions/phpunit@master
        with:
          version: 9.6
          bootstrap: vendor/autoload.php
          configuration: ./phpunit.xml
          args: --coverage-text
```

Am I doing something wrong?
