### ISSUE TITLE
Unable to execute composer-action.bash in act

### ISSUE THREAD

**Issue by ibindoff** [php-actions/composer#119]
```
      - name: Do composer install for SAP backend
        uses: php-actions/composer@v6.1.0
        with:
          php_version: "8.2"
          container_workdir: backend
          working_dir: backend
```

Executing with act. Providing GITHUB_TOKEN et al. via .secrets file. e.g. `act -b --secret-file my.secrets`

```
| Building PHP 8.2 with extensions:  ...
| /var/run/act/workflow/6-composite-composer_run.sh: line 4: /var/run/act/actions/php-actions-composer@v6.1.1/composer-action.bash: Permission denied
```
Issue:
Since v6.1.1 we're unable to execute this script in the container. 6.1.0 does not exhibit this same error.

Possible fix:
Seems like a simple permissions error, need to add +x?
