### ISSUE TITLE
Unsure why 'Error code 5' occurs

### ISSUE THREAD

**Issue by dumityty** [php-actions/composer#125]
Hi, I'm encountering an error when running an action to update a composer package, however it's not quite clear what the problem actually is and no matter how many debugging options (-vvv) I add I just can't tell what the error actually is.

I have the following step to update a package:
```
- name: Update Drupal package with dependencies
      uses: php-actions/composer@8a65f0d3c6a1d17ca4800491a40b5756a4c164f3 #v6
      with:
        version: '2.6.0'
        php_version: '8.1'
        php_extensions: gd
        progress: true
        ssh_key: ${{ secrets.SSH_KEY }}
        ssh_key_pub: ${{ secrets.SSH_KEY_PUB }}
        command: update ${{ inputs.PACKAGE }}:${{ inputs.VERSION }}
        args:  --prefer-dist --optimize-autoloader --no-interaction --with-dependencies
```

When I run it to update for example `drupal/admin_toolbar:^3.4` I get a 'normal looking' output but the step ends in an `Error: Process completed with exit code 5.` error and doesn't continue to the next steps. (I could technically ignore this and allow the next steps to run with `if: always()` but wouldn't want to do that in case there will ever be an actual error from updating the package.)

![Image](https://github.com/user-attachments/assets/040299c2-c45b-4117-81de-5d782e86787f)

![Image](https://github.com/user-attachments/assets/be759cfe-a8db-4177-925b-23ef6bdcc745)

Running the same command locally results in the package and its direct dependencies being updated and no further errors occur:

![Image](https://github.com/user-attachments/assets/3e107834-da6c-4149-9f44-a213710d2fda)

I wouldn't have thought the messages at the top for `Dependency drupal/classy is also a root requirement. Package has not been listed as an update argument, so keeping locked at old version. Use --with-all-dependencies (-W) to include root dependencies.`, would cause issues since those are warnings from what I understand (?).
Everything works fine locally despite of those. And ideally I'm not looking at running it with -W to update the other packages.

Is there any way of figuring out that the `exit code 5` is and why it happens?
