### ISSUE TITLE
composer validate not possible

### ISSUE THREAD

**Issue by siad007** [php-actions/composer#13]
It is possible to validate `composer.json` by using the command `composer validate`.

Using it in a workflow like:
```
  - name: Validate composer.json
        uses: php-actions/composer@v2
        with:
          command: validate
```

Will fail with this error:
```
Command: composer validate --no-interaction --no-suggest --no-progress

                                                          
  [Symfony\Component\Console\Exception\RuntimeException]  
  The "--no-suggest" option does not exist.               
                                                          

validate [--no-check-all] [--no-check-lock] [--no-check-publish] [-A|--with-dependencies] [--strict] [--] [<file>]
```
