### ISSUE TITLE
issue with bcmath being required but not found

### ISSUE THREAD

**Issue by bapcltd-marv** [php-actions/composer#14]
have got bcmath being successfully installed by `shivammathur/setup-php@v2`, but `php-actions/composer@v2` fails saying that ext-bcmath is not found.

**Comment by g105b** [comment]
Extensions and runtimes are not shared between actions. I'm currently working on a way to configure PHP more coarsely (version, extensions, etc.)

Could you share your yml configuration at all?

**Comment by bapcltd-marv** [comment]
```yml
name: PHP Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: Static Analysis & Testing
    runs-on: ubuntu-latest

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        coverage: none
        extensions: bcmath

    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache Files
      uses: actions/cache@v2
      with:
        path: |
          ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install dependencies
      uses: php-actions/composer@v2
      with:
        ssh_key: ${{ secrets.A }}
        ssh_key_pub: ${{ secrets.B }}

    - name: Run Tests
      run: composer run tests
```
