### ISSUE TITLE
Only works from root

### ISSUE THREAD

**Issue by afilina** [php-actions/composer#15]
I can't specify the path where my composer.json file is located.

**Comment by g105b** [comment]
Hi @afilina ,

I'll look into this and provide you with an example soon.

**Comment by g105b** [comment]
Hi @afilina,

I have included the `--working-dir` flag that was missing from this action previously. You can now set it as an input to your action to change the working directory.

Example:

```yml
name: CI
on: [push]
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: php-actions/composer@master
        with:
          working_dir: path/to/other/directory
```

Alternatively, `bBy setting the `COMPOSER` env variable it is possible to set the filename of `composer.json` to something else.

Example:

```yml
name: CI
on: [push]
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: php-actions/composer@master
        env:
          COMPOSER: composer-other.json
```

Please let me know if you need anything else, I'm happy to help.

**Comment by FrEaKmAn** [comment]
Sorry to comment an old issue, but can you confirm that env logic is working as I cannot get it to work?

works
```
- uses: php-actions/composer@master
  with:
    php_version: 7.3
    working_dir: ./server/
```

doesn't work

```
- uses: php-actions/composer@master
  with:
    php_version: 7.3
  env:
    COMPOSER: ./server/composer.json
```
