### ISSUE TITLE
Feature request: Custom command arguments

### ISSUE THREAD

**Issue by dgw** [php-actions/composer#4]
I attempted to use a custom command with arguments:

```
[Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "install --working-dir ./submodule --no-suggest --prefer-dist" is not defined.
```

The step configuration:

```yaml
      - name: Install PHP dependencies
        uses: php-actions/composer@v1
        with:
          command: install
          args: --working-dir ./submodule --no-suggest --prefer-dist
```

Being able to use [php-actions/composer](https://github.com/php-actions/composer) with arguments would be nicer than our current workflow including [shivammathur/setup-php](https://github.com/shivammathur/setup-php), as this is a self-contained Docker action.

_**Note:** I've had to redact the actual `--working-dir` value because the example is taken from an internal project at work, but the directory name should be irrelevant._

**Comment by g105b** [comment]
Thanks for opening this. I will look into this and report back after some testing.

**Comment by navarr** [comment]
Hi I've ran into a similar issue trying to use this action to generate an archive

```
[Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "archive --format=zip --dir=./build" is not defined.  
```

Trying to use the command as thus:
```
      - name: Generate Composer Artifact
        uses: php-actions/composer@v1
        with:
          command: archive --format=zip --dir=./build
```

(aside: Hi @dgw, fancy meeting you here)

**Comment by navarr** [comment]
I guess my question would be, are the quotes in `entrypoint` around `$@` necessary?  I believe this examples would work without them, and I'm not sure what scenarios they were added to avoid

**Comment by georgezim85** [comment]
Worked for me like this:
```yml
- name: Install Composer packages dependencies
  uses: php-actions/composer@v1
  with:
    command: composer
    args: install --no-suggest --prefer-dist
```
