### ISSUE TITLE
Error unknown blob during the execution

### ISSUE THREAD

**Issue by giuliolastra** [php-actions/composer#41]
Hello, 
thanks in advance for support, I'm quite new of github actions and I was trying to archieve a simple checkout of my private repo, in order to copy to a VPS.
I archieved it about 10 days ago, using your **php-actions/composer@v5** but today,  when I tried to run the actions (after adding just a few lines in my project) I had a totally different execution of your action that ended with this:
```
unknown blob
Error: Process completed with exit code 1.
```

I tried also to rollback commit and running same execution but no luck.

How can I solve?

Thanks!

**Comment by g105b** [comment]
Hi, can you share anything like the configuration yml of your repository so I can take a look?

**Comment by giuliolastra** [comment]
Sure, here's the first part of my action. 

```yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2.3.4
      with:
        path: ./
        ref: ${{ github.event.inputs.branch }}
    - name: Checking files
      run: ls -lA
    - name: Composer Install
      uses: php-actions/composer@v5
      with:
        php_version: 7.4
        progress: yes
        dev: no
```

While on the error I had:

```
1019b4d6a141: Layer already exists
86d905c1f58e: Layer already exists
22573737ba76: Layer already exists
777b2c648970: Layer already exists
unknown blob
Error: Process completed with exit code 1.
```

By the way I've runned it now, and the execution was the composer's standard one, ending with a success. But I changed absolutely nothing.
