### ISSUE TITLE
I'm having trouble when trying use

### ISSUE THREAD

**Issue by isaacmsl** [php-actions/composer#48]
I've add a Github Action on my repo to run PHPUnit tests.
Github action:
```yml
name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
```

At first time, it return an error on "Run php-actions/composer@v5". The log said:

```
Successfully tagged docker.pkg.github.com/isaacmsl/ez-action/php-actions_composer_ez-action:php-latest-build2
The push refers to repository [docker.pkg.github.com/isaacmsl/ez-action/php-actions_composer_ez-action]
e6df99478f76: Preparing
[...]
8fe0a997b1cf: Preparing
[...]
8fe0a997b1cf: Waiting
[...]
cb381a32b229: Waiting
83b32e5508b0: Retrying in 5 seconds
[...]
e6df99478f76: Retrying in 4 seconds
8886df9fe953: Pushed
5c78d57ff020: Retrying in 4 seconds
[...]
04eb62f9289c: Retrying in 1 second
8fe0a997b1cf: Pushed
[...]
83b32e5508b0: Pushed
unknown blob
Error: Process completed with exit code 1.
```

Please help me
