### ISSUE TITLE
cat output.log no such file

### ISSUE THREAD

**Issue by markkimsal** [php-actions/composer#52]
```
            - name: Install Dependencies
              uses: php-actions/composer@v5
              with:
                  dev: yes
                  version: 1
                  php_version: 7.3
                  command: install
                  args: -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist --ignore-platform-reqs
```

The output just says
```
cat: /home/runner/work/accounts/accounts/output.log: No such file or directory
```
![image](https://user-images.githubusercontent.com/54099/113593891-f63a8d00-9604-11eb-8555-1c46097631ff.png)
