### ISSUE TITLE
Unable to run exec command due to --no-interaction flag

### ISSUE THREAD

**Issue by JasonTheAdams** [php-actions/composer#60]
Greetings!

I'm trying to run the following wp-cli command:
```yml
      - name: Install composer dependencies and generate pot file
        uses: php-actions/composer@v5
        with:
          command: exec wp i18n make-pot ${{github.workspace}} ${{github.workspace}}/languages/give.pot
```

The command fails, however, as the --no-interaction flag:
```
Command: composer exec wp i18n make-pot /home/runner/work/givewp/givewp /home/runner/work/givewp/givewp/languages/give.pot --no-interaction
Error: Process completed with exit code 1.
```

I suspect the assumption is that the command is a native composer command, and not the exec command. So an exception probably needs to be made for the exec command to not add any additional flags.
