### ISSUE TITLE
Composer unable to apply patches

### ISSUE THREAD

**Issue by joz-cti** [php-actions/composer#62]
This github action is unable to apply composer patches, the specific add on I am using is - https://github.com/cweagans/composer-patches
It is strange that if I use "composer install"  instead of this package then composer can apply the patches.
The add on requires "patch" to be installed on the server, I can confirm this was installed on the Ubuntu OS.
Are there permission restriction on what this action can do? Perhaps it cannot write/update to the the file system?

**Comment by g105b** [comment]
Hi @joz-cti,

This isn't something I'm familiar with, but I'll look into it for you as soon as I can.

Any follow up information here would be useful, but I'll pick it up as soon as I get some time.

Cheers,
Greg.

**Comment by dschmidtadv** [comment]
> composer-patches

I am facing the same issue.

**Comment by g105b** [comment]
Hi @joz-cti 

I'm following up on this as the issue is still unresolved. Please could you help me by showing me the output of your failing workflow? I can't see any reason why this wouldn't work out of the box, as Ubuntu does indeed have diff and patch installed by default.

Thanks,
Greg.

**Comment by joz-cti** [comment]
Hi Greg,

I will look into this tomorrow and provide you the log

Joz

**Comment by g105b** [comment]
Interesting - it looks like this is run within `sh` rather than `bash`, and the `patch` command isn't available by default. I'll look into this on the [example-composer](https://github.com/php-actions/example-composer) repository and see if I can replicate, and once it's replicable it's fixable.

**Comment by g105b** [comment]
I've added the `help wanted` label because I'm not sure how to fix this myself.

**Comment by pingevt** [comment]
@g105b - First, I'm no expert on Github actions, and could be completely off base, so take it for what its worth. But this is the rabbit trail I've gone down for looking into this.

- Sounds like `patch` command isn't found and I would assume this is a docker issue
- You're creating the docker image here: https://raw.githubusercontent.com/php-actions/php-build/cee5b9fa9fbc4c888e7a62bbb7b8eade18e3c56b/php-build.bash
- Looks like the base is only a php base image, not a composer base image
- Looking at a composer docker file ([example](https://github.com/composer/docker/blob/9f1f0e2f42f8a525b4b0ba3b2f33429fae7d07bf/2.4/Dockerfile)) you can see they are explicitly installing `patch` in the first run command

So after that rabbit trail... I think adding `patch` at least to your docker image in the `RUN apk` command is the first place to start.

Also, I guess I would also ask, why not use a composer docker image?

**Comment by pingevt** [comment]
@g105b 

OK - I forked 2 of your repos, and I think I have this working.

Simply put, in your php-build.bash file in php-actions/php-build, I changed:

`RUN apk add --update --no-cache zip git bash openssh"`
to 
`RUN apk add --update --no-cache bash coreutils git make openssh patch unzip zip"`

I added in a few others from composer's docker file.

I want to keep looking into this on my site to make sure it really is working.

**Comment by g105b** [comment]
Oh that looks a lot simpler than I thought. I'll make that change on `php-build`, unless you want to raise a PR for it, then we can test it for real on https://github.com/php-actions/example-composer

**Comment by pingevt** [comment]
Just added a PR. I worked on it a little more yesterday and is working for my case.

**Comment by g105b** [comment]
Will update this ticket later with the outcome of testing.

**Comment by g105b** [comment]
Hi - this looks to be working now on a test branch. Please can you give it a run by using this step in your workflow file:

```yml
      - name: Install dependencies
        uses: php-actions/composer@bluecadet
```

**Comment by g105b** [comment]
The bluecadet branch is using the PR raised by @pingevt.

Thanks!

**Comment by pingevt** [comment]
@g105b Finally got around to looking into this... At first pass it looks like it is working for my use case.

**Comment by shawnachieve** [comment]
Has this issue been fixed?  I've tried using both the v6 and the bluecadet builds, but still get the same errors reported in this ticket when applying patches.

Here is my workflow:
```
jobs:
  update-composer-lock:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Update lock file"
        uses: php-actions/composer@bluecadet
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        with:
          php_version: "8.0"
          php_extensions: bcmath gd
          ssh_key: ${{ secrets.SSH_KEY }}
          ssh_key_pub: ${{ secrets.SSH_KEY_PUB }}
          command: update
          args: -vvv --with-all-dependencies
      - uses: actions/upload-artifact@v3
        with:
          name: debug-output
          path: output.log
```

The error response I get is:
```
 - Applying patches for drupal/core
    https://git.drupalcode.org/project/drupal/-/merge_requests/71.diff (Support entities that are neither content nor config entities[node/3042467])
Executing command (CWD): patch '-p2' --no-backup-if-mismatch -d 'web/core' < '/tmp/63efb2b950e20.patch'
patch '-p2' --no-backup-if-mismatch -d 'web/core' < '/tmp/63efb2b950e20.patch'
sh: patch: not found

   Could not apply patch! Skipping
```
