### ISSUE TITLE
503 Service Unavailable docker.pkg.github.com

### ISSUE THREAD

**Issue by konnisoelch** [php-actions/composer#63]
I am getting the following error while trying to install my packages.

Pulling docker.pkg.github.com/company/project/php-actions_composer_project:php-7.4-build2
Error response from daemon: received unexpected HTTP status: 503 Service Unavailable

```
- name: Install dependencies
        uses: php-actions/composer@v6
        with:
          ssh_key: ${{ secrets.ssh_key }}
          ssh_key_pub: ${{ secrets.ssh_key_pub }}
          php_version: 7.4
          args: --profile --ignore-platform-reqs
```
