### ISSUE TITLE
Process completed with exit code 1.

### ISSUE THREAD

**Issue by konnisoelch** [php-actions/composer#65]
Somehow running composer install is currently not working? 

My config:

```
- name: Install dependencies
        uses: php-actions/composer@v6
        with:
          ssh_key: ${{ secrets.ssh_key }}
          ssh_key_pub: ${{ secrets.ssh_key_pub }}
          php_version: 7.4
          version: 2
          args: --profile --ignore-platform-reqs
```

Error-Log:
```
Run php-actions/composer@v6
  with:
    php_version: 7.4
    version: 2
    args: --profile --ignore-platform-reqs
    command: install
    interaction: no
    dev: yes
    progress: no
    quiet: no
Run bash <(curl -s https://raw.githubusercontent.com/php-actions/php-build/330b13bbb1eadd05bbb627477c1549cd7e62e406/php-build.bash) composer \ && /home/runner/work/_actions/php-actions/composer/v6/composer-action.bash || { echo "::group::Debug output" ; cat /home/runner/work/di-typo3/di-typo3/output.log ; echo "::endgroup::" ; exit 1; }
  bash <(curl -s https://raw.githubusercontent.com/php-actions/php-build/330b13bbb1eadd05bbb627477c1549cd7e62e406/php-build.bash) composer \ && /home/runner/work/_actions/php-actions/composer/v6/composer-action.bash || { echo "::group::Debug output" ; cat /home/runner/work/di-typo3/di-typo3/output.log ; echo "::endgroup::" ; exit 1; }
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    ACTION_VERSION: 2
    ACTION_PHP_VERSION: 7.4
    ACTION_PHP_EXTENSIONS: 
    ACTION_TOKEN: ***
    ACTION_COMMAND: install
    ACTION_ONLY_ARGS: 
    ACTION_INTERACTION: no
    ACTION_DEV: yes
    ACTION_PROGRESS: no
    ACTION_QUIET: no
    ACTION_ARGS: --profile --ignore-platform-reqs
    ACTION_SSH_KEY: 
    ACTION_SSH_KEY_PUB: 
    ACTION_SSH_DOMAIN: 
    ACTION_WORKING_DIR: 
    ACTION_MEMORY_LIMIT: 
Debug output
  Running php-build composer
  WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json.
  Configure a credential helper to remove this warning. See
  https://docs.docker.com/engine/reference/commandline/login/#credentials-store
  
  Login Succeeded
  Pulling docker.pkg.github.com/bergwerk/di-typo3/php-actions_composer_di-typo3:php-7.4-build2
  php-7.4-build2: Pulling from bergwerk/di-typo3/php-actions_composer_di-typo3
  a0d0a0d46f8b: Already exists
  153eea49496a: Pulling fs layer
  11efd0df1fcb: Pulling fs layer
  b3f3214c344d: Pulling fs layer
  39841fde121a: Pulling fs layer
  b391f58f02a2: Pulling fs layer
  d683414984c6: Pulling fs layer
  b5ec125c3128: Pulling fs layer
  45f685e0ebe6: Pulling fs layer
  451b18210adb: Pulling fs layer
  39841fde121a: Waiting
  b391f58f02a2: Waiting
  d683414984c6: Waiting
  b5ec125c3128: Waiting
  45f685e0ebe6: Waiting
  451b18210adb: Waiting
  11efd0df1fcb: Verifying Checksum
  11efd0df1fcb: Download complete
  153eea49496a: Verifying Checksum
  153eea49496a: Download complete
  b3f3214c344d: Verifying Checksum
  b3f3214c344d: Download complete
  b391f58f02a2: Verifying Checksum
  b391f58f02a2: Download complete
  153eea49496a: Pull complete
  39841fde121a: Verifying Checksum
  39841fde121a: Download complete
  d683414984c6: Verifying Checksum
  d683414984c6: Download complete
  b5ec125c3128: Verifying Checksum
  b5ec125c3128: Download complete
  11efd0df1fcb: Pull complete
  b3f3214c344d: Pull complete
  45f685e0ebe6: Verifying Checksum
  45f685e0ebe6: Download complete
  39841fde121a: Pull complete
  b391f58f02a2: Pull complete
  451b18210adb: Verifying Checksum
  451b18210adb: Download complete
  d683414984c6: Pull complete
  b5ec125c3128: Pull complete
  45f685e0ebe6: Pull complete
  451b18210adb: Pull complete
  Digest: sha256:c5389009a2843ed48a30da1b5a6d456371d54d7abc2e9aee92a89e2d8527a595
  Status: Downloaded newer image for docker.pkg.github.com/bergwerk/di-typo3/php-actions_composer_di-typo3:php-7.4-build2
  docker.pkg.github.com/bergwerk/di-typo3/php-actions_composer_di-typo3:php-7.4-build2
  Docker tag: docker.pkg.github.com/bergwerk/di-typo3/php-actions_composer_di-typo3:php-7.4-build2
Error: Process completed with exit code 1.
```

**Comment by fhuitelec** [comment]
Hi :wave: 

We have the same symptoms: what seems to be a valid action run which ends with an **1** exit code.

```
- name: Configure Composer
  uses: php-actions/composer@v6
  with:
    version: 2
    command: config -g github-oauth.github.com ${{ secrets.XXX }}
```

<details><summary>Run php-actions/composer@v6</summary><p>

```
Run php-actions/composer@v6
  with:
    version: 2
    command: config -g github-oauth.github.com ***
    php_version: latest
    interaction: no
    dev: yes
    progress: no
    quiet: no
```

</p></details>

<details><summary>Run bash</summary><p>

```
Run bash <(curl -s https://raw.githubusercontent.com/php-actions/php-build/330b13bbb1eadd05bbb627477c1549cd7e62e406/php-build.bash) composer \ && /home/runner/work/_actions/php-actions/composer/v6/composer-action.bash || { echo "::group::Debug output" ; cat /home/runner/work/ets-offer-manager-api/ets-offer-manager-api/output.log ; echo "::endgroup::" ; exit 1; }
  bash <(curl -s https://raw.githubusercontent.com/php-actions/php-build/330b13bbb1eadd05bbb627477c1549cd7e62e406/php-build.bash) composer \ && /home/runner/work/_actions/php-actions/composer/v6/composer-action.bash || { echo "::group::Debug output" ; cat /home/runner/work/ets-offer-manager-api/ets-offer-manager-api/output.log ; echo "::endgroup::" ; exit 1; }
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    ACTION_VERSION: 2
    ACTION_PHP_VERSION: latest
    ACTION_PHP_EXTENSIONS: 
    ACTION_TOKEN: ***
    ACTION_COMMAND: config -g github-oauth.github.com ***
    ACTION_ONLY_ARGS: 
    ACTION_INTERACTION: no
    ACTION_DEV: yes
    ACTION_PROGRESS: no
    ACTION_QUIET: no
    ACTION_ARGS: 
    ACTION_SSH_KEY: 
    ACTION_SSH_KEY_PUB: 
    ACTION_SSH_DOMAIN: 
    ACTION_WORKING_DIR: 
    ACTION_MEMORY_LIMIT: 
```

</p></details>

<details><summary>Debug output</summary><p>

```
  Running php-build composer
  WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json.
  Configure a credential helper to remove this warning. See
  https://docs.docker.com/engine/reference/commandline/login/#credentials-store
  
  Login Succeeded
  Pulling docker.pkg.github.com/XXXX/XXXX/php-actions_composer_XXXXX:php-latest-build2
  php-latest-build2: Pulling from XXXX/XXXX/php-actions_composer_XXXXX
  a0d0a0d46f8b: Already exists
  153eea49496a: Pulling fs layer
  11efd0df1fcb: Pulling fs layer
  b3f3214c344d: Pulling fs layer
  9abd2f85688c: Pulling fs layer
  83d85b95eb4c: Pulling fs layer
  923d73ddadfa: Pulling fs layer
  711b5c4b02a7: Pulling fs layer
  ee08fa481788: Pulling fs layer
  1b1659af753c: Pulling fs layer
  9abd2f85688c: Waiting
  83d85b95eb4c: Waiting
  923d73ddadfa: Waiting
  711b5c4b02a7: Waiting
  ee08fa481788: Waiting
  1b1659af753c: Waiting
  b3f3214c344d: Verifying Checksum
  b3f3214c344d: Download complete
  153eea49496a: Verifying Checksum
  153eea49496a: Download complete
  153eea49496a: Pull complete
  11efd0df1fcb: Verifying Checksum
  11efd0df1fcb: Download complete
  11efd0df1fcb: Pull complete
  83d85b95eb4c: Verifying Checksum
  83d85b95eb4c: Download complete
  9abd2f85688c: Verifying Checksum
  9abd2f85688c: Download complete
  b3f3214c344d: Pull complete
  9abd2f85688c: Pull complete
  83d85b95eb4c: Pull complete
  711b5c4b02a7: Verifying Checksum
  711b5c4b02a7: Download complete
  ee08fa481788: Verifying Checksum
  ee08fa481788: Download complete
  923d73ddadfa: Verifying Checksum
  923d73ddadfa: Download complete
  1b1659af753c: Verifying Checksum
  1b1659af753c: Download complete
  923d73ddadfa: Pull complete
  711b5c4b02a7: Pull complete
  ee08fa481788: Pull complete
  1b1659af753c: Pull complete
  Digest: sha256:937d8829fcfd4480faa2ae4a086b8d9b8e932e0b4b528f578457f2544125c21f
  Status: Downloaded newer image for docker.pkg.github.com/XXXX/XXXX/php-actions_composer_XXXXX:php-latest-build2
  docker.pkg.github.com/XXXX/XXXX/php-actions_composer_XXXXX:php-latest-build2
  Docker tag: docker.pkg.github.com/XXXX/XXXX/php-actions_composer_XXXXX:php-latest-build2
Error: Process completed with exit code 1.
```
</p></details>

**Comment by g105b** [comment]
No problem. I've just subscribed to Github Status updates so I am better informed in the future of any outages.

Have fun!

**Comment by netdjw** [comment]
Hi, I just try to use this action and get same error.

I use this YAML file:
```yml
name: PR
on: [push]
jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v6
      with:
        php_version: 8
        working_dir: laravel/
    - name: Run PHPCS inspection
      run: |
        cd laravel/
        php artisan key:generate
        php artisan jwt:secret
        ./vendor/squizlabs/php_codesniffer/bin/phpcs -p src/ app/ config/ resources/**/*.php routes/ tests/
```

And this is the debug message:

```
Script @php artisan ide-helper:generate handling the post-autoload-dump event returned with error code 1
Debug output
Running php-build composer
  WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json.
  Configure a credential helper to remove this warning. See
  https://docs.docker.com/engine/reference/commandline/login/#credentials-store
  
  Login Succeeded
  Pulling docker.pkg.github.com/user/repo/php-actions_composer_dcms:php-8-build2
  WARNING: ⚠️ Failed to pull manifest by the resolved digest. This registry does not
  	appear to conform to the distribution registry specification; falling back to
  	pull by tag.  This fallback is DEPRECATED, and will be removed in a future
  	release.  Please contact admins of https://docker.pkg.github.com./ ⚠️
  
  php-8-build2: Pulling from user/repo/php-actions_composer_dcms
  59bf1c3509f3: Already exists
  7c7da25b2876: Pulling fs layer
  2bc599114627: Pulling fs layer
  927a0b37a45a: Pulling fs layer
  e721f6667a51: Pulling fs layer
  0bdbed47885a: Pulling fs layer
  5fb1dc6050d0: Pulling fs layer
  5f8bec7fe9f5: Pulling fs layer
  1a77502cdea2: Pulling fs layer
  6a5bdd93d53c: Pulling fs layer
  e721f6667a51: Waiting
  0bdbed47885a: Waiting
  5fb1dc6050d0: Waiting
  5f8bec7fe9f5: Waiting
  1a77502cdea2: Waiting
  6a5bdd93d53c: Waiting
  927a0b37a45a: Verifying Checksum
  927a0b37a45a: Download complete
  2bc599114627: Download complete
  7c7da25b2876: Download complete
  7c7da25b2876: Pull complete
  2bc599114627: Pull complete
  0bdbed47885a: Verifying Checksum
  0bdbed47885a: Download complete
  927a0b37a45a: Pull complete
  e721f6667a51: Verifying Checksum
  e721f6667a51: Download complete
  5f8bec7fe9f5: Verifying Checksum
  5f8bec7fe9f5: Download complete
  5fb1dc6050d0: Verifying Checksum
  5fb1dc6050d0: Download complete
  e721f6667a51: Pull complete
  0bdbed47885a: Pull complete
  1a77502cdea2: Verifying Checksum
  1a77502cdea2: Download complete
  6a5bdd93d53c: Verifying Checksum
  6a5bdd93d53c: Download complete
  5fb1dc6050d0: Pull complete
  5f8bec7fe9f5: Pull complete
  1a77502cdea2: Pull complete
  6a5bdd93d53c: Pull complete
  Digest: sha256:427bb74ea026a93adc3bf94f73d2e68fa43014dfdd4cde3c74c2e742cb8039a2
  Status: Downloaded newer image for docker.pkg.github.com/user/repo/php-actions_composer_dcms:php-8-build2
  docker.pkg.github.com/user/repo/php-actions_composer_dcms:php-8-build2
  Docker tag: docker.pkg.github.com/user/repo/php-actions_composer_dcms:php-8-build2
  No private keys supplied
  Command: composer install --working-dir=laravel/ --no-progress --no-interaction
  Skipping env variable PWD
  Skipping env variable HOME
  Skipping env variable SHLVL
  Skipping env variable PATH
Error: Process completed with exit code 1.
```

In my local docker container it works fine. I use this PHP version in my container:

```
PHP 8.0.16 (fpm-fcgi) (built: Feb 18 2022 22:24:19)
Copyright (c) The PHP Group
Zend Engine v4.0.16, Copyright (c) Zend Technologies
```

Any idea what's wrong?
