### ISSUE TITLE
php_version argument is ignored?

### ISSUE THREAD

**Issue by AttLii** [php-actions/composer#67]
Hey,

I’m using following workflow to run my phpunit tests:
```
name: Pull Request
on: [pull_request]
jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
        with:
          php_version: 7.4
          version: 2
      - run: composer test
```

When I print out php version inside tests with `phpversion()` or `PHP_VERSION`, the output is `8.0.12`. I created a test print [here](https://github.com/AttLii/headless-converter/runs/4248942187?check_suite_focus=true), see "Run composer test" step. Am I using this action wrong or is it something in your action?
