### ISSUE TITLE
"Resource not accessible by integration" error

### ISSUE THREAD

**Issue by adambiggs** [php-actions/composer#70]
Trying to get this action working, but I'm seeing "Resource not accessible by integration" errors on every build.

Neither of the fixes mentioned in #39 and #66 worked for me.

```
Successfully built 165ada25111a
Successfully tagged docker.pkg.github.com/my-org/my-repo/php-actions_composer_my-repo:php-latest-build2
The push refers to repository [docker.pkg.github.com/my-org/my-repo/php-actions_composer_my-repo]
7eba071b370c: Preparing
912d9c054022: Preparing
9310d54608c1: Preparing
5a02989682c4: Preparing
503898301ef3: Preparing
df2f9abed396: Preparing
dcd0ffda58b8: Preparing
c29d319c8043: Preparing
8a76a297762e: Preparing
8d3ac3489996: Preparing
df2f9abed396: Waiting
dcd0ffda58b8: Waiting
c29d319c8043: Waiting
8a76a297762e: Waiting
8d3ac3489996: Waiting
denied: Resource not accessible by integration
Error: Process completed with exit code 1.
```

This is running on a private repo, using the `push` event, with the following config:

```yml
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          args: --prefer-dist --no-interaction --no-progress --working-dir=./path/to/subdirectory
```

**Comment by g105b** [comment]
Hi, I'll take a look at this, but I haven't seen the "Resource not accessible by integration" error before. Please take a look at the https://github.com/php-actions/example-composer repository for a reference project that is known to be working. There are various different Actions YML configs in that project that test various different aspects.

Would you be able to please check the permissions under Settings > Actions > Actions permissions ?

![enable actions](https://user-images.githubusercontent.com/26739/92512177-66eb0980-f1dc-11ea-834a-6f47b34ffcb2.png)

**Comment by adambiggs** [comment]
It doesn't seem like I'm doing anything out of the ordinary compared with the example configurations from https://github.com/php-actions/example-composer.

Also I checked the actions permissions on my repo, and while the options are slightly different from your screenshot, the repo has full Actions permissions:

![image](https://user-images.githubusercontent.com/857229/144915857-adbcebb8-14ab-4ba2-b055-b8b24af4ceb4.png)

**Comment by g105b** [comment]
OK thanks for the update. I'll take a look into this. Is the repository in question open or closed source, and is it part of an organisation?

**Comment by adambiggs** [comment]
Yes, the repo is private and is part of an organization.

**Comment by g105b** [comment]
Please could you check in the organisation's settings page, as there are action-specific permissions in there.

**Comment by adambiggs** [comment]
Seems like the organization permissions shouldn't be stopping anything either:
![image](https://user-images.githubusercontent.com/857229/145912784-0f7bc437-1bb0-4955-872e-806ab19160fb.png)

**Comment by g105b** [comment]
I'll reach out to Github Support for a resolution on this, as I can't replicate the issue, and the error message seems very specific.

Two things to confirm beforehand: 

1) I expect I already know the answer to this, but if you re-run the action, this is the same outcome each time?
2) On order to get quick builds, php-actions caches the built images on the target repository (you'll see this under the packages tab on https://github.com/orgs/ORGANISATION_NAME/packages ) - please can you delete any packages from here and try again to rule out a caching issue?

**Comment by g105b** [comment]
P.S. I would also like to know which php-actions packages are available within your organisation, as I would expect a broken build for whatever reason should not be cached, but I'm not sure.

**Comment by adambiggs** [comment]
1. Yes, I saw the same outcome after re-running the action multiple times.
2. No packages were ever created in the organization packages page.

**Comment by g105b** [comment]
Thanks for the info, I'm escalating this to Github as it seems to be an actions issue. Will report back here.

**Comment by courtney-miles** [comment]
I am experiencing the same issue on a public repo.

I am new to Github actions (this is the first I have drafted one) so I'm not confident that the mistake is not mine.

You can see the failing action at https://github.com/frictionlessdata/tableschema-php/runs/4734356485?check_suite_focus=true

I had attempted to use the action from https://github.com/frictionlessdata/datapackage-php/blob/main/.github/workflows/ci.yml verbatim, but it failed with the same error.

To verify the mistake is not mine, I simplified the action as much as I understood how.

```yml
name: CI
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest

        name: frictionlessdata/tableschema-php test

        steps:
            - uses: actions/checkout@v2

            - name: Validate composer.json & composer.lock
              uses: php-actions/composer@v6
              with:
                  command: validate --strict
```
