### ISSUE TITLE
curl command not found

### ISSUE THREAD

**Issue by WybeBaT** [php-actions/composer#76]
I'm trying to use composer@v2 to install dependencies, however I get an error saying the curl command is not found

**/__w/_temp/2236824c-0115-4211-aa6e-f45dbd70b342.sh: line 1: curl: command not found**

I also ran into #61, which I worked around with the "Touch output file (temporary fix)" step.

Below is my workflow file, commented lines are things that I've tried to fix the issue:

```
name: Build Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  php-stan:
    name: PHPStan
    runs-on: self-hosted
    container:
      image: ubuntu:20.04
      options: --rm

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Touch output file (temporary fix)
        run: |
          mkdir -p /home/github-runner/github/actions-runner/_work/MyProject/MyProject
          touch /home/github-runner/github/actions-runner/_work/MyProject/MyProject/output.log

#      - name: Setup PHP 8
#        uses: shivammathur/setup-php@v2
#        env:
#          runner: self-hosted
#        with:
#          php-version: '8.0'
#          extensions: curl

#      - name: Install curl
#        run: apt-get install -y curl

      - name: Set up Composer
        uses: php-actions/composer@v6
        with:
          php_version: 8.0
#          php_extensions: curl
          version: 2

      - name: Set up and run PHPStan
        uses: php-actions/phpstan@v3
        with:
          path: src/
          level: 8
```

If I comment out the composer action, the PHPStan action gives me the same *curl: command not found** error

**EDIT**:
The Install curl step above didn't work because I needed to do apt-get update first:

```
      - name: Install curl
        run: |
          apt-get update
          apt-get install -y curl
```

However, the composer package still doesn't work. It returns 1 and gives an empty Debug Output:

```
Debug output
Error: Process completed with exit code 1.
```

And just to be complete: When I manually install curl and composer. The @php-actions/phpstan action fails, with the same returns 1 and empty Debug Output as above.

**EDIT 2**:
I decided to save the output.log as artifact after the phpstan action. Inside it, I get the following error:
```
Running php-build phpstan
/dev/fd/63: line 53: docker: command not found
```
