### ISSUE TITLE
Error on composer 2 syntax error: unexpected newline

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [php-actions/composer#80]
Hi all,
I have a problem with our GitHub actions when we try to use composer 2 instead of 1.
I tried to specify 2.x, 2.2.12 but we receive always:

```
/usr/local/bin/composer: line 2: 
```

If I use composer 2 we have a PHP version problem because we are supporting PHP 7.1

This is a link to see the error:
https://github.com/phparkitect/arkitect/runs/6582531104?check_suite_focus=true#step:17:101

I have seen this issue very similar but I would like to know if it's possible to fix it or if we need to use composer 1: 
https://github.com/php-actions/composer/issues/79

Thanks.

**Comment by gsdevme** [comment]
The PR does resolve the issue but no v7 tag has been created. If you swap to using the master branch directly it should work. 

So use `php-actions/composer@master` vs `php-actions/composer@v6` Could do with v7 being tagged though to ease this. 

Something like 

```
        uses: php-actions/composer@master
        with:
          php_version: ${{ matrix.php }}
          version: 2.2.x
```
