### ISSUE TITLE
the composer version cannot be defined more precisely than the "major" version

### ISSUE THREAD

**Issue by Un1matr1x** [php-actions/composer#87]
I tried to define the composer version as described [here in the readme file](https://github.com/php-actions/composer#using-different-versions-of-php-or-composer).

If I only define the major-version the[ workflow file](https://github.com/Just-Another-Weather-Site/playground/blob/33064b1d3f32c9b5a9f3dd60e96bd3c21850e5e0/.github/workflows/validate.yaml) looks like this
```yaml
name: Validate

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Validate dependencies
        uses: php-actions/composer@v6.0.0
        with:
          command: validate
          php_version: "8.0.1"
          version: 2
```
and the [workflow passes](https://github.com/Just-Another-Weather-Site/playground/runs/7705413402?check_suite_focus=true)

if I change the version to [2.2](https://github.com/Just-Another-Weather-Site/playground/commit/f1b5ddf97d1f359602166b11b38849934883a110), [2.x](https://github.com/Just-Another-Weather-Site/playground/commit/4625e7d3c48817b3801915372df315028c5bc365) or ["2.2"](https://github.com/Just-Another-Weather-Site/playground/commit/b6ac212e78966b1fedc96895c91305b2dc0323c7) they all fail.

The failed workflows can be seen below and the debug logs are also preserved in a private gist

Version   | Workflow | Logs
         2.2 | [failed](https://github.com/Just-Another-Weather-Site/playground/actions/runs/2809200352) | [log](https://gist.githubusercontent.com/Un1matr1x/3231e18f713334e517c2c0dc2085c47b/raw/3cd94cfd49313b73f3b4f30b9f89a109d45abbab/ComposerVersion2.2.log)
         2.x | [failed](https://github.com/Just-Another-Weather-Site/playground/actions/runs/2809230412) | [log](https://gist.githubusercontent.com/Un1matr1x/3231e18f713334e517c2c0dc2085c47b/raw/3cd94cfd49313b73f3b4f30b9f89a109d45abbab/ComposerVersion2.x.log)
       "2.2" | [failed ](https://github.com/Just-Another-Weather-Site/playground/actions/runs/2809206037)| [log](https://gist.githubusercontent.com/Un1matr1x/3231e18f713334e517c2c0dc2085c47b/raw/3cd94cfd49313b73f3b4f30b9f89a109d45abbab/ComposerVersion%25222.2%2522.log)

What am I doing wrong?
