### ISSUE TITLE
Install PHP extensions?

### ISSUE THREAD

**Issue by rossjcooper** [php-actions/composer#9]
Is it possible to install PHP extensions using this action? E.g.
```yml
...
 - name: Install depenedencies
      uses: php-actions/composer@v1
      with:
        extensions: exif
...
```
