### ISSUE TITLE
Composer unable to apply patches

### ISSUE THREAD

**Issue by lukaszpilka** [php-actions/composer#98]
I created a new Issue for #62 which looks like not resolved.
I am still getting the "sh: patch: not found" error.

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@master
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.OLD_GITHUB_ORG_TOKEN }}"} }'
        with:
          dev: no
          args: --optimize-autoloader -vvv
          php_version: "8.1"
          version: 2.3.10
          php_extensions: redis gnupg apcu zip gd mysqli pdo_mysql bz2 curl exif intl opcache

The error response I get is:

    Applying patches for drupal/core
    https://www.drupal.org/files/issues/2022-08-01/1464354-enum-solution.patch (Solution for ENUM datatype for MySQL)
    Executing command (CWD): patch '-p2' --no-backup-if-mismatch -d 'docroot/core' < '/tmp/641d4e6733326.patch'
    patch '-p2' --no-backup-if-mismatch -d 'docroot/core' < '/tmp/641d4e6733326.patch'
    sh: patch: not found

**Comment by RobLoach** [comment]
Ran into this issue. It seems like the alpine container that it's using doesn't have `patch` installed. As a stop-gap, I switched over to using [shivammathur/setup-php](https://github.com/shivammathur/setup-php) and [ramsey/composer-install](https://github.com/ramsey/composer-install).

```
    - name: PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "8.1.11"

    - name: Composer
      uses: ramsey/composer-install@v2
      with:
        composer-options: "--ignore-platform-reqs"
```

**Comment by dmetzler1988** [comment]
Same issue here - so we needed to switch to `ramsey/composer-install` that our patch could be installed.
Hopefully there will be soon a new release with installed `patch` library - so that we can switch back to this `php-actions` action.

**Comment by adam-vessey** [comment]
Just ran into this. Bit of digging around, [looks like `HEAD`/`master` would be fine; however, but the current `v6`/`v6.1.1` is still referencing `cee5b9fa9fbc4c888e7a62bbb7b8eade18e3c56b`, the commit](https://github.com/php-actions/composer/compare/v6...master#diff-1243c5424efaaa19bd8e813c5e6f6da46316e63761421b3e5f5c8ced9a36e6b6L105-R105) before [the patch fix](https://github.com/php-actions/php-build/commit/3a2162134977ccc8129c97a13b58a6290e7d5580).

**Comment by pingevt** [comment]
@adam-vessey - how did you delete the `{repo}/php-actions_composer_{repo}`?

**Comment by pingevt** [comment]
Although its a few commits behind now, I've been pointing to a separate branch that uses the the fix:

```
- name: Install composer dependencies
  uses: php-actions/composer@bluecadet
  with:
    php_version: ${{ env.PHP_VERSION }}
```

Which will apply patches, but looks like it is now a few commits behind current v6
